# -*- coding: utf-8 -*-
"""Laboratorio 6: ETL - P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gctt1eUGlYKxXaBgW5FGDMQSCcfqqlyS
"""

import pandas as pd
import os

def cargar_archivo_csv(ruta):
    try:
        return pd.read_csv(ruta, encoding='latin1')
    except FileNotFoundError:
        print("Archivo no encontrado. Verifica la ruta.")
    except pd.errors.ParserError:
        print("Error al procesar el archivo. Verifica el formato.")
    return pd.DataFrame()  # Retorna un DataFrame vacío si hay error

def limpiar_datos(df, columna='STATE'): #Elimina las filas con valores nulos en la columna especificada.

    return df[df[columna].notna()]

def guardar_como_xml(df, salida): #Guarda un DataFrame en formato XML en la ubicación dada

    try:
        os.makedirs(os.path.dirname(salida), exist_ok=True)
        df.to_xml(salida, index=False)
    except Exception as e:
        print(f"No se pudo guardar el archivo XML: {e}")

# Ejecución ETL
archivo_csv = '/content/drive/MyDrive/Bases Avanzadas /sales_data.csv'
archivo_xml = '/content/drive/MyDrive/Bases Avanzadas /sales_datos_filtrados.xml'

datos = cargar_archivo_csv(archivo_csv)

if not datos.empty:
    datos_filtrados = limpiar_datos(datos)
    guardar_como_xml(datos_filtrados, archivo_xml)
    print("Proceso ETL completado: archivo XML generado.")
else:
    print("No se pudo realizar el proceso ETL: el archivo está vacío o no se cargó.")